apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "s3"
        - name: DEBUG
          value: "1"
        readinessProbe:
          httpGet:
            path: /
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
